CREATE DATABASE IF NOT EXISTS moviesdb;
USE moviesdb;

CREATE TABLE IF NOT EXISTS regista (
  idR INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(255) NOT NULL UNIQUE,
  eta  INT NOT NULL
);

CREATE TABLE IF NOT EXISTS piattaforma (
  idP INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS film (
  idF   INT AUTO_INCREMENT PRIMARY KEY,
  titolo VARCHAR(255) NOT NULL UNIQUE,
  idR   INT NOT NULL,
  anno  INT NOT NULL,
  genere VARCHAR(100) NOT NULL,
  CONSTRAINT fk_film_regista FOREIGN KEY (idR) REFERENCES regista(idR)
  ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS dove_vederlo (
  idF  INT PRIMARY KEY,
  idP1 INT NULL,
  idP2 INT NULL,
  CONSTRAINT fk_dv_film  FOREIGN KEY (idF)  REFERENCES film(idF)
  ON DELETE CASCADE,
  CONSTRAINT fk_dv_p1    FOREIGN KEY (idP1) REFERENCES piattaforma(idP),
  CONSTRAINT fk_dv_p2    FOREIGN KEY (idP2) REFERENCES piattaforma(idP),
  CONSTRAINT chk_two_distinct CHECK (idP1 IS NULL OR idP2 IS NULL OR idP1 <> idP2)
);

CREATE INDEX idx_film_anno ON film(anno);
CREATE INDEX idx_regista_eta ON regista(eta);
CREATE INDEX idx_dv_p1 ON dove_vederlo(idP1);
CREATE INDEX idx_dv_p2 ON dove_vederlo(idP2);
